version: '2'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - "9000:9000"
    volumes: 
      - ./data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: zookeeper:3.4.10
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:1.0.0
    container_name: kafka
    ports: 
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: elasticsearch
    volumes:
     - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - node.attr.zone=eu-west-1b
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.1.1
    container_name: metricbeat
    volumes: 
      - "./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml"
      - "/proc:/hostfs/proc:ro"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      # - "/:/hostfs:ro"
    # network_mode: host
    links:
      - elasticsearch
      - kibana
    command: "metricbeat run -e --setup -e -system.hostfs=/hostfs"
    user: root